version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: local-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    restart: unless-stopped

volumes:
  mongo-data:
